#!/usr/bin/env python3
import json

# Gallery 翻译数据
gallery_en = {
  "badge": {
    "label": "QUALITY",
    "text": "Video Quality Gallery"
  },
  "title": "Stunning AI-Generated Videos",
  "description": "Explore our gallery of videos created with Sora 2 and Veo 3.1",
  "tabs": {
    "realistic": "Realistic",
    "ugc": "UGC Style",
    "3d": "3D Animation"
  },
  "categories": {
    "realistic": {
      "title": "Realistic Style Videos",
      "description": "Professional quality realistic videos generated by AI",
      "videos": [
        {
          "id": "realistic-1",
          "title": "AI Spokesperson",
          "description": "Professional AI-generated spokesperson presenting smartphone product"
        },
        {
          "id": "realistic-2",
          "title": "Coffee Latte Art",
          "description": "Close-up shot of barista creating latte art with steamed milk"
        },
        {
          "id": "realistic-3",
          "title": "City Timelapse",
          "description": "Time-lapse of modern city skyline at twilight with dramatic colors"
        }
      ]
    },
    "ugc": {
      "title": "UGC Style Videos",
      "description": "Authentic user-generated content style videos for social media",
      "videos": [
        {
          "id": "ugc-1",
          "title": "Unboxing Experience",
          "description": "First-person POV unboxing premium headphones with genuine excitement"
        },
        {
          "id": "ugc-2",
          "title": "Fitness Workout",
          "description": "Energetic fitness workout with jumping jacks in bright living room"
        },
        {
          "id": "ugc-3",
          "title": "Avocado Toast",
          "description": "Hands preparing colorful healthy avocado toast in sunny kitchen"
        }
      ]
    },
    "3d": {
      "title": "3D Animation Videos",
      "description": "Creative 3D animated videos with Pixar-style quality",
      "videos": [
        {
          "id": "3d-1",
          "title": "3D Headphones Showcase",
          "description": "3D animated product showcase with wireless headphones rotating"
        },
        {
          "id": "3d-2",
          "title": "Cute 3D Character",
          "description": "Cute 3D animated character walking happily, Disney-Pixar style"
        },
        {
          "id": "3d-3",
          "title": "3D Logo Animation",
          "description": "3D brand logo animation with geometric shapes assembling"
        }
      ]
    }
  }
}

# 读取现有文件
with open('i18n/messages/en/NanoBananaVideo.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# 添加 Gallery
data['Gallery'] = gallery_en

# 写回文件
with open('i18n/messages/en/NanoBananaVideo.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("✅ 英文翻译已添加")
