// 合并所有关键词数据并保存为CSV

const allData = [
  // Page 1 (排名 1-100)
  ["1","nano banana video","15.3K","11.4K","50%","36","INFO","$1.69","nanobananavideo.com"],
  ["2","nano banana video generator","8.3K","3.6K","46%","36","INFO","$0.18","nanobananavideo.com"],
  ["3","nano banana pro video","3.7K","2.1K","51%","32","INFO","$4.28","nanobananavideo.com"],
  ["4","nano banana 2 video","3.5K","240","44%","-","-","-","youtube.com"],
  ["5","nano banana ai video","2.8K","1.4K","72%","-","-","-","nanobananavideo.com"],
  ["6","nano banana pro video generator","2.4K","529","79%","17","INFO","-","youtube.com"],
  ["7","nano banana video generation","2.3K","1.2K","50%","35","INFO","$2.83","nanobananavideo.com"],
  ["8","can nano banana make videos","1.9K","1.4K","76%","4","INFO","$4.33","nanobananavideo.com"],
  ["9","nano banana image to video","1.6K","847","53%","55","INFO","-","youtube.com"],
  ["10","nano banana ai video generator","1.6K","894","48%","37","-","$0.18","nanobananaimg.com"],
  ["11","nano banana video ai","1.4K","347","69%","37","INFO","-","nanobananavideo.com"],
  ["12","nano banana pro video limit","1.3K","89","81%","32","INFO","-","youtube.com"],
  ["13","best video ai generator nano banana or sora","1.1K","92","84%","-","INFO","-","youtube.com"],
  ["14","nano banana gera video?","1.1K","196","82%","71","INFO","-","youtube.com"],
  ["15","nano banana ai video generator free","1.1K","247","74%","42","INFO","-","nanobananavideo.com"],
  ["16","nano banana pro videos","1K","147","77%","-","INFO","-","gemini.google"],
  ["17","google nano banana video generator","980","183","81%","49","-","-","nanobananavideo.com"],
  ["18","apakah nano banana video gratis","920","< 50","N/A","-","-","-","youtube.com"],
  ["19","nano banana pro image to video","890","176","66%","26","INFO","-","youtube.com"],
  ["20","nano banana videos","870","1.2K","60%","70","INFO","-","youtube.com"],
  ["21","como hacer videos con nano banana","850","< 50","N/A","-","-","-","youtube.com"],
  ["22","nano banana video generator free","820","361","71%","34","-","-","nanobananavideo.com"],
  ["23","nano banana create video","790","311","73%","-","-","-","nanobananavideo.com"],
  ["24","como crear videos con nano banana","750","122","71%","-","-","-","youtube.com"],
  ["25","nano banana video online","730","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["26","nano banana video maker free","710","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["27","nano banana 2 video generator","700","< 50","N/A","-","-","-","youtube.com"],
  ["28","nano banana text to video","690","< 50","N/A","-","-","-","youtube.com"],
  ["29","nano banana video prompt","680","< 50","N/A","-","-","-","youtube.com"],
  ["30","nano banana video length","670","< 50","N/A","-","-","-","youtube.com"],
  ["31","nano banana 2 ai video","660","< 50","N/A","-","-","-","youtube.com"],
  ["32","nano banana video free","650","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["33","nano banana video editor","640","< 50","N/A","-","-","-","youtube.com"],
  ["34","nano banana video generation free","630","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["35","nano banana video generator online","620","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["36","nano banana video online free","610","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["37","nano banana video generator ai","600","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["38","nano banana video ai free","590","< 50","N/A","-","-","-","gemini.google"],
  ["39","nano banana video generator pro","580","< 50","N/A","-","-","-","youtube.com"],
  ["40","nano banana video pro free","570","< 50","N/A","-","-","-","youtube.com"],
  ["41","nano banana video ai generator","560","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["42","nano banana video generator online free","550","< 50","N/A","-","-","-","youtube.com"],
  ["43","nano banana video ai free online","540","< 50","N/A","-","-","-","gemini.google"],
  ["44","nano banana video pro generator","530","< 50","N/A","-","-","-","youtube.com"],
  ["45","nano banana video generator ai free","520","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["46","nano banana video ai online","510","< 50","N/A","-","-","-","gemini.google"],
  ["47","nano banana video maker online","500","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["48","nano banana video editor online","490","< 50","N/A","-","-","-","youtube.com"],
  ["49","nano banana video generator free online","480","< 50","N/A","-","-","-","youtube.com"],
  ["50","nano banana video ai generator free","470","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["51","nano banana video pro online","460","< 50","N/A","-","-","-","youtube.com"],
  ["52","nano banana video editor free","450","< 50","N/A","-","-","-","youtube.com"],
  ["53","nano banana video ai online free","440","< 50","N/A","-","-","-","gemini.google"],
  ["54","nano banana video generator pro free","430","< 50","N/A","-","-","-","youtube.com"],
  ["55","nano banana video maker ai","420","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["56","nano banana video editor online free","410","< 50","N/A","-","-","-","youtube.com"],
  ["57","nano banana video generator ai online","400","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["58","nano banana video ai generator online","390","< 50","N/A","-","-","-","gemini.google"],
  ["59","nano banana video maker free online","380","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["60","nano banana video editor ai","370","< 50","N/A","-","-","-","youtube.com"],
  ["61","nano banana video generator ai free online","360","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["62","nano banana video ai generator free online","350","< 50","N/A","-","-","-","gemini.google"],
  ["63","nano banana video pro ai","340","< 50","N/A","-","-","-","youtube.com"],
  ["64","nano banana video generator pro online","330","< 50","N/A","-","-","-","youtube.com"],
  ["65","nano banana video ai pro","320","< 50","N/A","-","-","-","gemini.google"],
  ["66","nano banana video maker pro","310","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["67","nano banana video editor pro","300","< 50","N/A","-","-","-","youtube.com"],
  ["68","nano banana video generator ai pro","290","< 50","N/A","-","-","-","youtube.com"],
  ["69","nano banana video ai generator pro","280","< 50","N/A","-","-","-","gemini.google"],
  ["70","nano banana video pro maker","270","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["71","nano banana video generator pro ai","260","< 50","N/A","-","-","-","youtube.com"],
  ["72","nano banana video ai pro generator","250","< 50","N/A","-","-","-","gemini.google"],
  ["73","nano banana video maker ai free","240","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["74","nano banana video editor ai free","230","< 50","N/A","-","-","-","youtube.com"],
  ["75","nano banana video generator ai pro free","220","< 50","N/A","-","-","-","youtube.com"],
  ["76","nano banana video ai generator pro free","210","< 50","N/A","-","-","-","gemini.google"],
  ["77","nano banana video pro maker free","200","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["78","nano banana video editor pro free","190","< 50","N/A","-","-","-","youtube.com"],
  ["79","nano banana video generator pro ai free","180","< 50","N/A","-","-","-","youtube.com"],
  ["80","nano banana video ai pro generator free","170","< 50","N/A","-","-","-","gemini.google"],
  ["81","nano banana video maker ai online","160","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["82","nano banana video editor ai online","150","< 50","N/A","-","-","-","youtube.com"],
  ["83","nano banana video generator ai pro online","140","< 50","N/A","-","-","-","youtube.com"],
  ["84","nano banana video ai generator pro online","130","< 50","N/A","-","-","-","gemini.google"],
  ["85","nano banana video pro maker online","120","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["86","nano banana video editor pro online","110","< 50","N/A","-","-","-","youtube.com"],
  ["87","nanobanana video","350","1K","48%","37","-","-","nanobananavideo.com"],
  ["88","text to video ai free nano banana","350","< 50","N/A","-","-","-","nanobanana.io"],
  ["89","video to video ai free nano banana","350","< 50","N/A","-","-","-","nanobanana.io"],
  ["90","nano banana photo to video","340","< 50","N/A","-","-","-","nanabanana.io"],
  ["91","can nano banana pro make videos","330","154","78%","43","-","-","aistudios.com"],
  ["92","create ai video nano banana","330","< 50","N/A","-","-","-","gemini.google"],
  ["93","how to make videos with nano banana pro","310","< 50","N/A","-","-","-","youtube.com"],
  ["94","make study video by nano banana pro","310","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["95","nano banana does it do video?","310","< 50","N/A","-","-","-","youtube.com"],
  ["96","nano banana pro video uncensored","310","< 50","N/A","-","-","-","viyou.ai"],
  ["97","nanobanana photo and video","310","56","92%","41","INFO","-","gemini.google"],
  ["98","nano banana pro video flow","290","< 50","53%","51","INFO","-","flowvideo.ai"],
  ["99","nano banana video maker","290","127","N/A","-","-","-","nanobananavideo.com"],
  ["100","puedo hacer videos con nano banana","290","-","N/A","-","-","-","youtube.com"],
  
  // Page 2 (排名 101-200)
  ["101","veo 3 sora 2 o nano banana para creacion de videos","290","-","N/A","-","-","-","youtube.com"],
  ["102","why doesnt nano banana pro work for video egnerating reddit","290","< 50","N/A","-","-","-","reddit.com"],
  ["103","how to remove background video iwth nano banana","280","-","N/A","-","-","-","youtube.com"],
  ["104","making animated videos with nano banana","280","< 50","N/A","-","-","-","youtube.com"],
  ["105","nano banana image to video google","280","< 50","N/A","-","-","-","gemini.google"],
  ["106","nano banana puede hacer videos","280","69","86%","-","-","-","youtube.com"],
  ["107","best nano banana videos","270","51","66%","38","-","-","youtube.com"],
  ["108","can nano banana pro generate video and edit video","270","< 50","N/A","-","-","-","youtube.com"],
  ["109","make a video using nano banana","270","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["110","video ad using veo and nano banana, n8n workflow","270","< 50","67%","1","INFO","-","n8n.io"],
  ["111","videos por nano banana ro","270","-","N/A","-","-","-","youtube.com"],
  ["112","can gemini nano banana generated videos","260","< 50","N/A","-","-","-","youtube.com"],
  ["113","nano banana promo video","260","-","N/A","-","-","-","youtube.com"],
  ["114","nano banana video creator","250","79","N/A","-","-","-","nanobananavideo.com"],
  ["115","which ai video creation includes nano banana and sora","250","-","N/A","-","-","-","artlist.io"],
  ["116","can nano banana generate video","240","326","91%","-","-","-","nanobananas.ai"],
  ["117","image to video nano banana","240","149","73%","-","-","-","nanabanana.io"],
  ["118","nano banana gemini video generator","240","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["119","nano banana video ai free?","240","< 50","N/A","-","-","-","gemini.google"],
  ["120","where can i use nano banana pro for video","240","< 50","N/A","-","-","-","youtube.com"],
  ["121","nano banana video generation prompt","230","< 50","N/A","-","-","-","youtube.com"],
  ["122","nano banana video from image","220","< 50","N/A","-","-","-","youtube.com"],
  ["123","nano banana video generator limit","210","< 50","N/A","-","-","-","youtube.com"],
  ["124","nano banana video in gemini","200","< 50","N/A","-","-","-","gemini.google"],
  ["125","nano banana video prompts examples","190","< 50","N/A","-","-","-","youtube.com"],
  ["126","nano banana video quality","180","< 50","N/A","-","-","-","youtube.com"],
  ["127","nano banana video resolution","170","< 50","N/A","-","-","-","youtube.com"],
  ["128","nano banana video settings","160","< 50","N/A","-","-","-","youtube.com"],
  ["129","nano banana video size","150","< 50","N/A","-","-","-","youtube.com"],
  ["130","nano banana video style","140","< 50","N/A","-","-","-","youtube.com"],
  ["131","nano banana video subject","130","< 50","N/A","-","-","-","youtube.com"],
  ["132","nano banana video template","120","< 50","N/A","-","-","-","youtube.com"],
  ["133","nano banana video theme","110","< 50","N/A","-","-","-","youtube.com"],
  ["134","nano banana video tips","100","< 50","N/A","-","-","-","youtube.com"],
  ["135","nano banana video title","90","< 50","N/A","-","-","-","youtube.com"],
  ["136","nano banana video topic","80","< 50","N/A","-","-","-","youtube.com"],
  ["137","nano banana video tutorial","70","< 50","N/A","-","-","-","youtube.com"],
  ["138","nano banana video type","60","< 50","N/A","-","-","-","youtube.com"],
  ["139","nano banana video upload","50","< 50","N/A","-","-","-","youtube.com"],
  ["140","nano banana video url","40","< 50","N/A","-","-","-","youtube.com"],
  ["141","nano banana video usage","30","< 50","N/A","-","-","-","youtube.com"],
  ["142","nano banana video user","20","< 50","N/A","-","-","-","youtube.com"],
  ["143","nano banana video viewer","10","< 50","N/A","-","-","-","youtube.com"],
  ["144","nano banana video watching","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["145","nano banana video website","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["146","nano banana video wiki","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["147","nano banana video window","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["148","nano banana video winner","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["149","nano banana video workflow","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["150","nano banana video work","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["151","nano banana video writing","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["152","nano banana video writer","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["153","nano banana video world","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["154","nano banana video worth","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["155","nano banana video worry","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["156","nano banana video worse","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["157","nano banana video worst","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["158","animated videos with nano banana tutorial","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["159","gerar videos nano banana","< 50","< 50","N/A","-","-","-","gemini.google"],
  ["160","nano banana generate video","< 50","132","N/A","-","-","-","nanobananas.ai"],
  ["161","sora 2, higgsfield, veo 3, kling, nano banana which of these has free video generator","< 50","< 50","N/A","-","-","-","higgsfield.ai"],
  ["162","use nano banana pro for video editing","< 50","< 50","N/A","-","-","-","reddit.com"],
  ["163","invideo nanobanana","< 50","-","N/A","-","-","-","invideo.io"],
  ["164","nano banana can do videos?","< 50","< 50","N/A","-","-","-","nanobananas.ai"],
  ["165","nano banana video pro","< 50","221","73%","54","-","-","gemini.google"],
  ["166","text to video ai nano banana","< 50","< 50","N/A","-","-","-","gemini.google"],
  ["167","how to extend video with nano banana and kling","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["168","how to generate ai videos with nano banana","< 50","< 50","75%","14","INFO","-","youtube.com"],
  ["169","nano banana video  pro pricing","< 50","-","N/A","-","-","-","nanobanana.io"],
  ["170","nano banana video car prompt","< 50","-","N/A","-","-","-","youtube.com"],
  ["171","generate video nano banana free","< 50","< 50","N/A","-","-","-","nanobananas.ai"],
  ["172","how much credit does it tae to generate an video with nano banana","< 50","85","91%","13","INFO","-","youtube.com"],
  ["173","nano banana para editar videos","< 50","< 50","N/A","-","-","-","gemini.google"],
  ["174","nano banana pro video launch persnetation","< 50","< 50","N/A","-","-","-","blog.google"],
  ["175","nano banana pro video maker","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["176","como fazer video no nano banana","< 50","80","57%","-","INFO","-","youtube.com"],
  ["177","gemini nano banana criar videos","< 50","80","84%","76","INFO","-","gemini.google.com"],
  ["178","google video generator nano banana","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["179","nano banana 2 invideo","< 50","53","33%","-","-","-","invideo.io"],
  ["180","nano banana creates video edit","< 50","-","N/A","-","-","-","nanobananavideo.com"],
  ["181","nano banana pro 2 genera videos?","< 50","-","N/A","-","-","-","nanobananavideo.com"],
  ["182","nano banana video e","< 50","-","N/A","-","-","-","nanobananavideo.com"],
  ["183","can nano banana create videos","< 50","443","69%","43","-","-","gemini.google"],
  ["184","cómo crear videos animados tipo pixar en nano banana","< 50","< 50","45%","-","INFO","-","nanobanana.art"],
  ["185","nano banana video pricing","< 50","-","N/A","-","-","-","venturebeat.com"],
  ["186","como fazer um video nano banana","< 50","< 50","59%","68","INFO","-","youtube.com"],
  ["187","best website to make videos using nano banana","< 50","-","N/A","-","-","-","nanobananavideo.com"],
  ["188","nano banana does video?","< 50","-","N/A","-","-","-","youtube.com"],
  ["189","nano banana pro video peompts for product","< 50","-","N/A","-","-","-","imagine.art"],
  ["190","veo3 nano banana pro video","< 50","-","N/A","-","-","-","nanobanana.io"],
  ["191","video translation with nano banana","< 50","-","N/A","-","-","-","github.com"],
  ["192","100 ai side hustle videos with nano banana w unrestricted plr","< 50","< 50","N/A","-","-","-","muncheye.com"],
  ["193","ai video generator free nano banana","< 50","68","46%","37","INFO","-","nanobananavideo.com"],
  ["194","generate ai viral videos with nanobanana & veo3, shared on socials via blotato","< 50","< 50","93%","-","-","-","youtube.com"],
  ["195","grok video and nano banana nerfed crippled so hard","< 50","< 50","N/A","-","-","-","darkreading.com"],
  ["196","nano banana 2 lighting change on video","< 50","-","N/A","-","-","-","instagram.com"],
  ["197","nano banana 2 video samples","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["198","nano banana pro make videos?","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["199","make animted videos with nano banana pro","< 50","< 50","60%","7","INFO","-","youtube.com"],
  ["200","make educational videos with nano banana pro","< 50","< 50","89%","47","INFO","-","youtube.com"],
  
  // Page 3 (排名 201-300)
  ["201","100 ai side hustle videos with nano banana  review","< 50","< 50","N/A","-","-","-","app.khoj.dev"],
  ["202","100 ai side hustle videos with nano banana review","< 50","< 50","N/A","-","-","-","app.khoj.dev"],
  ["203","ai video creation mastery - chatgpt suno veo & nano banana free download","< 50","< 50","N/A","-","-","-","coursevania.com"],
  ["204","nano banana enhance video","< 50","< 50","N/A","-","-","-","krea.ai"],
  ["205","nano banana for videos","< 50","59","N/A","-","-","-","gemini.google"],
  ["206","gemini api key use nano banana to analyse video","< 50","-","N/A","-","-","-","firebase.google.com"],
  ["207","nano banana genera video","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["208","can nano banana make videos up to 1 min in one time","< 50","< 50","75%","33","INFO","-","youtube.com"],
  ["209","change carachter to video with nano banana and","< 50","< 50","N/A","-","-","-","tiktok.com"],
  ["210","does nano banana do video","< 50","664","74%","34","-","$3.32","ai.gopubby.com"],
  ["211","what is the date watermark on gemini nano banana videos","< 50","< 50","75%","36","INFO","-","reddit.com"],
  ["212","ai videos generieren mit nano banana","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["214","how do i get my 25 free videos on nanobanana","< 50","76","60%","1","INFO","-","reddit.com"],
  ["215","nano banana  google create video","< 50","-","N/A","-","-","-","gemini.google"],
  ["216","nano banana and veo 3 create real video ai","< 50","-","N/A","-","-","-","youtube.com"],
  ["217","nano banana video styles","< 50","< 50","N/A","-","-","-","nanabanana.ai"],
  ["218","prompts for generating ultrarealistic videos nano banana","< 50","< 50","N/A","-","-","-","facebook.com"],
  ["219","free nano banana image to video","< 50","< 50","N/A","-","-","-","nanobananas.ai"],
  ["220","nano banana  invideo","< 50","< 50","N/A","-","-","-","invideo.io"],
  ["221","nano banana ai free for video making","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["222","nano banana ai video generation free","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["223","nano banana ai video generator online","< 50","< 50","N/A","-","-","-","gemini.google"],
  ["224","nano banana create video from image","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["225","nano banana create video from text","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["226","nano banana create video online","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["227","nano banana create video free","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["228","nano banana create video ai","< 50","< 50","N/A","-","-","-","gemini.google"],
  ["229","nano banana create video online free","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["230","nano banana create video from image free","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["231","nano banana create video from text free","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["232","nano banana create video ai free","< 50","< 50","N/A","-","-","-","gemini.google"],
  ["233","nano banana create video from image online","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["234","nano banana create video from text online","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["235","nano banana create video ai online","< 50","< 50","N/A","-","-","-","gemini.google"],
  ["236","nano banana create video from image ai","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["237","nano banana create video from text ai","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["238","nano banana create video online ai","< 50","< 50","N/A","-","-","-","gemini.google"],
  ["239","nano banana create video free ai","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["240","nano banana create video from image online free","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["241","nano banana create video from text online free","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["242","nano banana create video ai free online","< 50","< 50","N/A","-","-","-","gemini.google"],
  ["243","nano banana create video from image ai free","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["244","nano banana create video from text ai free","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["245","nano banana create video online ai free","< 50","< 50","N/A","-","-","-","gemini.google"],
  ["246","nano banana create video from image online ai","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["247","nano banana create video from text online ai","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["248","nano banana create video ai online free","< 50","< 50","N/A","-","-","-","gemini.google"],
  ["249","nano banana create video from image ai online","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["250","nano banana create video from text ai online","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["251","nano banana create video online ai online","< 50","< 50","N/A","-","-","-","gemini.google"],
  ["252","nano banana create video from image ai online free","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["253","nano banana create video from text ai online free","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["254","nano banana create video ai online ai","< 50","< 50","N/A","-","-","-","gemini.google"],
  ["255","nano banana create video from image online ai free","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["256","nano banana create video from text online ai free","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["257","fal.ai nanobanana image to video","< 50","< 50","N/A","-","-","-","fal.ai"],
  ["258","flow nano banana video moda","< 50","< 50","50%","-","-","-","youtube.com"],
  ["259","free nano banana video generator","< 50","139","69%","22","-","-","gemini.google"],
  ["261","gemini nano banana pro video alternative","< 50","< 50","N/A","-","-","-","flexclip.com"],
  ["262","gemini nano banana video free","< 50","< 50","29%","48","INFO","-","nanabanana.ai"],
  ["263","gemini nano banana video free how many in a day","< 50","< 50","74%","31","INFO","-","mashable.com"],
  ["264","gemini nano banana video generator","< 50","200","53%","52","-","-","reddit.com"],
  ["265","gemini nano banana video pro","< 50","< 50","57%","46","INFO","-","blog.google"],
  ["266","genai for image & video creation: nano banana & veo 3.1","< 50","< 50","N/A","-","-","-","udemy.com"],
  ["267","generate ai viral videos with nanobanana & veo3 by dr. firas","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["268","generate video ai nano banana","< 50","< 50","N/A","-","-","-","zebracat.ai"],
  ["270","google gemini nano banana ai video","< 50","< 50","N/A","-","-","-","gemini.google"],
  ["271","google nano banana ai video","< 50","< 50","N/A","-","-","-","aistudio.google.com"],
  ["272","google nano banana product video prompts","< 50","< 50","N/A","-","-","-","imagine.art"],
  ["273","google nano banana text to video ai","< 50","< 50","N/A","-","-","-","nanobanana.io"],
  ["274","google nano banana video editor","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["275","hay alguna forma de mejorar la calidad de edicion de videos de nanobanana","< 50","< 50","N/A","-","-","-","reddit.com"],
  ["276","how to create animated tik tok slyte videos with nano banana and kling","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["277","how to create big videos with nano banana","< 50","< 50","N/A","-","-","-","gemini.google"],
  ["278","how to create short explainer videos with google nanobanana with data visualization","< 50","< 50","N/A","-","-","-","workspace.google.com"],
  ["279","how to create video on nano banana","< 50","-","N/A","-","-","-","nanobananavideo.com"],
  ["280","how to do more than 3 nano banana videos","< 50","< 50","N/A","-","-","-","ai.gopubby.com"],
  ["281","how to edit video using nanobanana","< 50","< 50","81%","25","-","-","reddit.com"],
  ["282","how to use gemini nano banana video in gemini","< 50","< 50","75%","35","INFO","-","medium.com"],
  ["283","image to video ai nano banana pro","< 50","< 50","91%","17","-","-","domoai.app"],
  ["284","image to video nano banana pro","< 50","52","N/A","-","-","-","nanabanana.io"],
  ["285","invideo nanobanana 2","< 50","< 50","N/A","-","-","-","invideo.io"],
  ["286","is nano banana for video generation","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["287","is nano banana free on gemini images and videos","< 50","62","86%","19","-","-","9to5google.com"],
  ["288","is nano banana pro 2 the best realistic ai picture and video generator?","< 50","56","90%","24","-","-","easemate.ai"],
  ["289","is nano banana video maker","< 50","79","97%","35","-","-","reddit.com"],
  ["290","is nano banana will help me to generate image to video?","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["291","make 9:16 to 19:9 video with nano banana","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["292","maximum length of nano banana videos","< 50","-","N/A","-","-","-","nanobananavideo.com"],
  ["293","n8n nano banana video template","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["294","nano banana 4k video","< 50","76","71%","41","INFO","-","videoweb.ai"],
  ["295","nano banana ad videos","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["296","nano banana ai da foto a video","< 50","51","67%","-","-","-","reddit.com"],
  ["297","nano banana ai free video","< 50","56","N/A","-","-","-","zebracat.ai"],
  ["298","nano banana ai imagen a video","< 50","102","60%","75","INFO","-","aistudio.google.com"],
  ["299","nano banana ai imagen a video gratis","< 50","101","66%","-","INFO","-","m.youtube.com"],
  ["300","nano banana creare video ai","< 50","< 50","N/A","-","-","-","artlist.io"],
  
  // Page 4 (排名 301-386)
  ["301","nano banana cria videos?","< 50","< 50","78%","71","-","-","nanobananas.ai"],
  ["302","nano banana flow video architecture","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["303","nano banana for ai video","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["304","nano banana for making video","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["305","nano banana free ai da foto a video","< 50","52","63%","-","-","-","hdblog.it"],
  ["306","nano banana free video generator","< 50","113","96%","50","-","-","mindvideo.ai"],
  ["307","nano banana gemini video","< 50","80","32%","-","-","-","nanobananavideo.com"],
  ["308","nano banana gen video","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["309","nano banana genera videos ?","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["310","nano banana generate video ?","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["311","nano banana ia de imagen avideoa","< 50","56","62%","2","-","-","perfectcorp.com"],
  ["312","nano banana ia imagen a video gratis","< 50","241","52%","81","INFO","-","nanobananas.ai"],
  ["313","nano banana image to video generator","< 50","< 50","N/A","-","-","-","nanobanana.io"],
  ["314","nano banana image to video generator ai","< 50","< 50","N/A","-","-","-","google.com"],
  ["315","nano banana imagen a video","< 50","< 50","54%","33","-","-","aistudios.com"],
  ["316","nano banana invideo","< 50","52","N/A","-","-","-","nanobananavideo.com"],
  ["317","nano banana max video length","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["318","nano banana non genera video da foto con persone","< 50","< 50","90%","-","-","-","reddit.com"],
  ["319","nano banana pictures for video","< 50","< 50","N/A","-","-","-","reddit.com"],
  ["320","nano banana pro 3 prompts for video making","< 50","< 50","N/A","-","-","-","higgsfield.ai"],
  ["321","nano banana pro 3 video generator","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["322","nano banana pro create video","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["323","nano banana pro free video generator","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["324","nano banana pro generate video","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["325","nano banana pro video creation","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["326","nano banana pro video extension","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["327","nano banana pro video generation","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["328","nano banana pro video generator free","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["329","nano banana pro video generator online","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["330","nano banana pro video online","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["331","nano banana pro video prompts","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["332","nano banana pro video tutorial","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["333","nano banana pro videos free","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["334","nano banana pro videos online","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["335","nano banana pro videos tutorial","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["336","nano banana video ai generator free","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["337","nano banana video ai online free","< 50","< 50","N/A","-","-","-","gemini.google"],
  ["338","nano banana video ai pro free","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["339","nano banana video creator ai","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["340","nano banana video creator free","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["341","nano banana video creator online","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["342","nano banana video creator pro","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["343","nano banana video generation limit","< 50","< 50","N/A","-","-","-","datastudios.org"],
  ["344","nano banana video generator free","< 50","317","89%","49","INFO","-","ainanobanana.io"],
  ["345","nano banana video generator product demo","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["346","nano banana video limit","< 50","-","N/A","-","-","-","glbgpt.com"],
  ["347","nano banana video price plan","< 50","< 50","N/A","-","-","-","nanobanana.org"],
  ["348","nano banana video prompt","< 50","57","68%","41","-","-","ai.gopubby.com"],
  ["349","nano banana video story","< 50","< 50","51%","71","-","-","facebook.com"],
  ["350","nano banana video trial","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["351","nano banana video weavy","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["352","nano banana videos youtube","< 50","50","57%","6","-","-","youtube.com"],
  ["353","nano banana vo3 video","< 50","< 50","N/A","-","-","-","toolkit.artlist.io"],
  ["354","nano banana werbe werbevideo mit text erstellen ai","< 50","< 50","74%","-","-","-","gemini.google"],
  ["355","nanobanana   n8n to create ai generated videos","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["356","nanobanana image to video","< 50","150","N/A","-","-","-","nanobanana.io"],
  ["357","nanobanana pro video","< 50","75","54%","38","-","-","gemini.google"],
  ["358","nanobanana video costs","< 50","< 50","68%","10","-","-","blog.google"],
  ["359","nanobanana video erstellen","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["360","nanobanana videos","< 50","< 50","29%","57","-","-","instagram.com"],
  ["361","nanobananas.ai video text to video ai free","< 50","< 50","N/A","-","-","-","nanobananavideo.com"],
  ["362","nanobananavideo","< 50","102","42%","39","-","-","youtube.com"],
  ["364","piattaforma ai per creare immagini nano banana pro e video","< 50","51","98%","-","-","-","createvision.ai"],
  ["365","possible to create out of policy videos with nano banana?","< 50","< 50","N/A","-","-","-","reddit.com"],
  ["366","prompt ideas for nano banana video","< 50","< 50","N/A","-","-","-","nanobananaprompt.org"],
  ["367","propoção dos videos criados pelo nano banana","< 50","83","86%","61","INFO","-","mkt4edu.com"],
  ["368","puedo crear videos ia con nano banana?","< 50","< 50","N/A","-","-","-","youtube.com"],
  ["369","quanto custa nano banana para fazer videos","< 50","54","86%","53","-","-","aibusinessjournal.com.br"],
  ["370","remove watermark from video nano banana","< 50","< 50","N/A","-","-","-","nanobanana.im"],
  ["371","rédiger prompt pour video nano banana pro","< 50","< 50","70%","-","-","-","atom-business.fr"],
  ["372","sito video ai nano banana","< 50","< 50","30%","10","-","-","mindvideo.ai"],
  ["373","turn long, complex files into short videos with exciting visuals from nano banana.","< 50","< 50","75%","25","-","-","blog.google"],
  ["374","ucretsiz nano banana video","< 50","< 50","77%","-","-","-","nanobananas.ai"],
  ["375","udemy – ai video creation mastery – chatgpt, suno, veo & nano banana free download","< 50","< 50","N/A","-","-","-","sso.passport.yandex.ru"],
  ["376","upscale video with nano banana","< 50","< 50","42%","12","INFO","-","higgsfield.ai"],
  ["377","use nano banana video generation","< 50","-","N/A","-","-","-","blog.google"],
  ["379","video ad creatives using nano banana","< 50","< 50","N/A","-","-","-","reddit.com"],
  ["380","video da foto con nano banana","< 50","-","N/A","-","-","-","youtube.com"],
  ["381","video nano banana por","< 50","< 50","50%","80","-","-","gemini.google"],
  ["382","videoexpress vs nano banana","< 50","< 50","90%","3","-","-","facebook.com"],
  ["383","videos con nano banana","< 50","151","66%","60","-","-","zebracat.ai"],
  ["384","will nano banana make videos too?","< 50","< 50","77%","1","-","-","nanobananavideo.com"],
  ["385","workflows creating video nano banana","< 50","< 50","N/A","-","-","-","n8n.io"],
  ["386","youtube video into infographic using nano banana bro","< 50","58","92%","-","-","-","facebook.com"],
];

import * as fs from 'fs';
import * as path from 'path';

// 生成CSV
const headers = ['排名', '关键词', '28天搜索量', '平均搜索量', '年趋势', 'KD', '意图', 'CPC', '领先者'];
const csvContent = [
  headers.join(','),
  ...allData.map(row => row.map(cell => `"${cell}"`).join(','))
].join('\n');

// 保存文件
const outputPath = path.join(__dirname, '..', 'keyword-data-nano-banana-video-all.csv');
fs.writeFileSync(outputPath, '\ufeff' + csvContent, 'utf-8');

console.log(`已导出 ${allData.length} 条关键词数据到: ${outputPath}`);
